version: "3.4" 
 
services: 
    starireactblog: 
        image: starireactblog 
        container_name: starireactblog 
        build: 
            context: . 
            dockerfile: ./Dockerfile 
        environment: 
            NODE_ENV: production 
        ports: 
            - 7341:4173 
        restart: unless-stopped